# Generated by Django 4.2.4 on 2023-08-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prueba_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
